### PR TITLE
Fixes most `-Wall` warnings

### LINKED ISSUE #375: Does not compile cleanly with `-Wall`
ALPSCore emits a huge strings of warnings with `-Wall`, particularly in the HDF5 and the accumulators modules.

This makes it very ugly to enable `-Wall` by default (ideally also `-Wextra`, but I'm not that `-pedantic`).  By disabling `-Wall`, however, we hide a lot of potential problems in the development stage.  Also, it is just not good style to have warning-ridden code.

### PR DESCRIPTION
**Pull request by mwallerb**
Fixes #375 by fixing most instances of two types of warnings:

 * signed/unsigned integer comparison
 * unused parameters

### CODE REVIEW

File: accumulators/include/alps/accumulators/feature/binning_analysis.hpp [hunk 1]
```diff
@@ -255,7 +255,7 @@ namespace alps {
                         using alps::numeric::check_size;
 
                         B::operator()(val);
-                        if(B::count() == (1 << m_ac_sum2.size())) {
+                        if(static_cast<size_t>(B::count()) == (1UL << m_ac_sum2.size())) {
```
Comment (galexv) [inline accumulators/include/alps/accumulators/feature/binning_analysis.hpp]: Do we need this `static_cast<size_t>`?  `count()` is supposed to return `count_type<T>::type` which is `boost::uint64_t`. Maybe it's better to redefine it in [count.hpp:31](https://github.com/ALPSCore/ALPSCore/blob/master/accumulators/include/alps/accumulators/feature/count.hpp#L31)?

File: accumulators/include/alps/accumulators/feature/max_num_binning.hpp [hunk 2]
```diff
@@ -345,7 +345,7 @@ namespace alps {
                 void partition_bins(alps::mpi::communicator const & comm,
                                     std::vector<typename mean_type<B>::type> & local_bins,
                                     std::vector<typename mean_type<B>::type> & merged_bins,
-                                    int root) const
+                                    int /*root*/) const
```
Comment (galexv) [inline accumulators/include/alps/accumulators/feature/max_num_binning.hpp]: `partition_bins()` does not use `root` argument and it is not needed for any overload -- shall we eliminate it? (I guess it is here as a placeholder, if one day we decide to use `MPI_Reduce()` rather than `MPI_Allreduce()`...)

Comment (mwallerb) [reply accumulators/include/alps/accumulators/feature/max_num_binning.hpp]: Is it worth it? I mean the writing's on the wall anyway for `alps::accumulators`

File: mc/include/alps/mc/mpiadapter.hpp [hunk 3]
```diff
@@ -72,15 +72,15 @@ namespace alps {
                             alps::mpi::all_reduce(communicator,
                                                   has_count,
                                                   std::plus<size_t>());
-                    if (sum_counts == communicator.size()) {
+                    if ((int)sum_counts == communicator.size()) {
```
Comment (galexv) [inline mc/include/alps/mc/mpiadapter.hpp]: Not a big deal, but why C-style cast `(int)` rather than `static_cast<int>()`, for consistency with other places?

File: mc/include/alps/mc/mpiadapter.hpp [hunk 4]
```diff
@@ -72,15 +72,15 @@ namespace alps {
...
                         if (communicator.rank() == 0) {
                             typename Base::observable_collection_type::value_type merged = this->measurements[*it];
                             merged.collective_merge(communicator, 0);
                             partial_results.insert(*it, merged.result());
                         } else {
                             this->measurements[*it].collective_merge(communicator, 0);
                         }
-                    } else if (sum_counts > 0 && sum_counts < communicator.size()) {
+                    } else if (sum_counts > 0 && (int)sum_counts < communicator.size()) {
```
Comment (galexv) [inline mc/include/alps/mc/mpiadapter.hpp]: The same: not a big deal, but why C-style cast `(int)` rather than `static_cast<int>()`, for consistency with other places?

File: mc/include/alps/mc/mpiadapter.hpp (hunk 3 above)
Comment (mwallerb) [reply mc/include/alps/mc/mpiadapter.hpp]: Lazyness, mainly. Will fix it.

File: utilities/test/test_utils_test.cpp [hunk 5]
```diff
@@ -45,11 +45,11 @@ class TestUtilsTest : public ::testing::Test {
         const unsigned int nvals=range<value_type>::VALUE;
         std::vector<value_type> vals(nvals);
 
-        for (int i=0; i<nvals; ++i) {
+        for (int i=0; i<(int)nvals; ++i) {
```
Comment (galexv) [inline utilities/test/test_utils_test.cpp]: Maybe better to change index `i` to unsigned for consistency...
