### PR TITLE
Fixed infinite recursion in named accumulators assignment

### LINKED ISSUE #548: [legacy accumulators] Infinite recursion on named accumulator assignment
Caught by `clang++ -Wall` while working on issue #375: infinite recursion at line 26 of
https://github.com/ALPSCore/ALPSCore/blob/b6274b03e6326ce1dba0eb35b2289838eaff3a3c/accumulators/src/namedaccumulators.cpp#L23-L27
(and similar places). 
 
clang reports:
```diff
 [ 70%] Building CXX object accumulators/CMakeFiles/alps-accumulators.dir/src/namedaccumulators.cpp.o
 .../accumulators/src/namedaccumulators.cpp:25:9: 
-warning: all paths through this function
-    will call itself [-Winfinite-recursion]
        {
         ^
-.../accumulators/src/namedaccumulators.cpp:35:31: 
 note: in instantiation of member
-      function 'alps::accumulators::MeanAccumulator<float>::operator=' requested here
-        BOOST_PP_SEQ_FOR_EACH(ALPS_ACCUMULATOR_INST_MEAN_ACCUMULATOR, ~, ALPS_ACCUMULATOR_VALUE_TYPES_SEQ)
```

and indeed, a simple test along the lines:
```c++
   using alps::accumulators;
   MeanAccumulator<double> rhs("rhs");
   MeanAccumulator<double> lhs("lhs");
   lhs=rhs; // <-- Infinite recursion here!
```
confirms the warning.

### PR DESCRIPTION
**Pull request by galexv**
This should close #548.

Igor (@krivenko), if you have time, could you also have a brief look, please?

### CODE REVIEW

File: accumulators/test/assign_acc.cpp [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+        named_acc_type rhs("rhs");
+        rhs=rhs;
+        aa::accumulator_set aset;
+        aset << rhs;
+
+        EXPECT_NO_THROW(aa::accumulator_wrapper acc=aset["rhs"]; acc << 1 << 2);
+    }
+};
+
+#define MAKE_TESTS(_acc_,_type_)                                      \
```
Comment (krivenko) [inline accumulators/test/assign_acc.cpp]: I'd rather go with the standard `TYPED_TEST_CASE`/`TYPED_TEST` macros.
